=== NahuelMedinaPiconi/Tasques-amb-Grafics/dades/activitats.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tasks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="task" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="description" type="xs:string" minOccurs="0"/>
                            <xs:element name="date" type="xs:string" minOccurs="0"/>
                            <xs:element name="category" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="color" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="importance">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Alta"/>
                                    <xs:enumeration value="Mitjana"/>
                                    <xs:enumeration value="Baixa"/>
                                    <xs:enumeration value="Sense Prioritat"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="finished">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="false"/>
                                    <xs:enumeration value="true"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== NahuelMedinaPiconi/Tasques-amb-Grafics/dades/activitats_004.xml
<?xml version = "1.0" encoding="UTF-8"?>
<tasks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="activitats.xsd">
    <task id="task_001" importance="Alta" is_done="false">
        <title>Crear xml</title>
        <description>Fer un xml per importar en js</description>
        <date>2020-11-05</date>
        <category>
            <name>XML</name>
            <color>#00cec9</color>
        </category>
    </task>
    <task id="task_002" importance="Mitjana" is_done="false">
        <title>DTD</title>
        <description>Validar xml</description>
        <date>2020-12-05</date>
        <category>
            <name>DTD</name>
            <color>#00ce88</color>
        </category>
    </task>
    <task id="task_003" importance="Baixa" is_done="false">
        <title>JSON</title>
        <description>Fer un arxiu json</description>
        <date>2020-11-06</date>
        <category>
            <name>XML</name>
            <color>#00cec9</color>
        </category>
    </task>
    <task id="task_004" importance="Alta" is_done="false">
        <title>Instalar Ubuntu</title>
        <description>S'ha d'instal·lar ubuntu</description>
        <date>2022-10-23</date>
        <category>
            <name>SO</name>
            <color>#ffffff</color>
        </category>
    </task>
</tasks>
